# ---------- deps ----------
FROM node:24-alpine AS deps
WORKDIR /app

COPY package.json ./
RUN npm install


# ---------- builder ----------
FROM node:24-alpine AS builder
WORKDIR /app

# Build-time args (di-inject dari docker-compose)
ARG APP_ENV
ARG NEXT_PUBLIC_ENDPOINT_URL
ARG NEXT_PUBLIC_GA_ID

# Set jadi ENV supaya kebaca saat `npm run build`
ENV APP_ENV=$APP_ENV
ENV NEXT_PUBLIC_ENDPOINT_URL=$NEXT_PUBLIC_ENDPOINT_URL
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN rm -rf .next || true
RUN npm run build


# ---------- runner ----------
FROM node:24-alpine AS runner
WORKDIR /app

# Runtime args (opsional, tapi kita set lagi biar aman)
ARG APP_ENV
ARG NEXT_PUBLIC_ENDPOINT_URL
ARG NEXT_PUBLIC_GA_ID
ENV NODE_ENV=production

ENV APP_ENV=$APP_ENV
ENV NEXT_PUBLIC_ENDPOINT_URL=$NEXT_PUBLIC_ENDPOINT_URL
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

EXPOSE 3000
CMD ["npm", "run", "start"]
