services:
  be-portofolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be-sample-${ENV}
    command: >
      sh -c "
        npm run migrate &&
        npm run seed &&
        npm run start:prod
      "
    env_file:
      - .env
    # ports:
    #   - '${DOCKER_PORT}:3000'
    volumes:
      - ./public:/app/public
    network_mode: "host"
    restart: always